sudo: required
language: php

php:
  - 7.2

addons:
  sonarcloud:
    organization: "javi2gar"
    token:
      secure: "$SONAR_CLOUD_API_KEY" # encrypted value of your token

before_install:

  # login to docker registries (dockerhub)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:  

  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - vendor/bin/sonar-scanner

  - docker build -t vernedevelop/daw-conversor-2020:version1.0.0; .  
  #- docker tag vernedevelop/daw-conversor-2020 vernedevelop/daw-conversor-2020:version1.0.0;
   
deploy: 

  - provider: heroku
    api_key: 
      secure: "$HEROKU_API_KEY"
    app: daw-conversor-2020  
    
  - provider: script
    script:
      # push to dockerhub
      docker push vernedevelop/daw-conversor-2020;
    on:
      branch: master
